name: Renovate

on:
  schedule:
    - cron: 0 * * * * # every hour

  workflow_dispatch:
    inputs:
      debug:
        description: Debug logging
        required: true
        type: boolean
        default: false

      dryRun:
        description: Dry run
        required: true
        type: boolean
        default: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    name: Renovate

    steps:
      - name: Obtain token
        id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PK }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.token.outputs.token }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.debug == 'true' && 'debug' || 'info' }}
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun == 'true' && 'full' || '' }}
