name: Renovate

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run'
        required: true
        type: boolean
        default: false

      logLevel:
        description: 'Log level'
        required: true
        type: choice
        default: 'info'
        options:
        - info
        - debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    name: Renovate

    steps:
      - name: Obtain Renovate app token
        id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PK }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.token.outputs.token }}
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun && 'full' || '' }}
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
